apiVersion: storage.k8s.io/v1
kind: StorageClass
metadata:
  name: vsan-file-sc
provisioner: csi.vsphere.vmware.com
parameters:
  storagepolicyname: "k8s-vsan-storage"
  csi.storage.k8s.io/fstype: nfs4
